# Generated by Django 6.0.2 on 2026-05-14 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='impact',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='problem',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='solution',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('web', 'Web'), ('api', 'API'), ('fullstack', 'Full Stack'), ('ml', 'Machine Learning'), ('ai', 'AI'), ('da', 'Data Analysis')], max_length=100),
        ),
    ]
