# Generated by Django 6.0.2 on 2026-05-14 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_project_impact_project_problem_project_solution_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
    ]
