# Generated by Django 6.0.2 on 2026-05-15 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_remove_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='video_static',
            field=models.CharField(blank=True, help_text='Example: portfolio.mp4', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('web', 'Web'), ('api', 'API'), ('fullstack', 'Full Stack'), ('ml', 'Machine Learning'), ('ai', 'AI')], max_length=100),
        ),
    ]
